FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Expose Vite port
EXPOSE 5173

# Start frontend and allow connections from host
CMD ["npm", "run", "dev", "--", "--host"]
